apiVersion: v1
kind: ConfigMap
metadata:
  name: eelp-config
  namespace: eelp-production
  labels:
    app.kubernetes.io/part-of: eelp
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  RABBITMQ_HOST: "rabbitmq"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  CONFIG_REPO_PATH: "file:///config-repo"
  SPRING_PROFILES_ACTIVE: "production"
  INVENTORY_DB_URL: "jdbc:mysql://mysql-inventory:3306/inventory_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  LOAN_DB_URL: "jdbc:mysql://mysql-loan:3306/loan_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
